"""
Auto-generate LaTeX tables for the dissertation (Task 11).

Reads the JSON artifacts produced by the V&V scripts and emits
standalone .tex files suitable for ``\\input{}`` from any Quarto /
LaTeX chapter. Running this script after a V&V sweep keeps the
dissertation draft in lock-step with the committed Op^3 outputs.

Tables produced
---------------
  calibration_regression_table.tex   Task 1.3 reference comparison
  dnv_conformance_table.tex          Task 4.4 audit
  iec_conformance_table.tex          Task 4.5 audit
  sensitivity_tornado_table.tex      Task 1.4 ranking
  pisa_cross_val_table.tex           Task 3.1e (AWAITING_VERIFY flagged)
  oc6_phase2_table.tex               Task 4.x (AWAITING_VERIFY flagged)

Run:
    python scripts/generate_latex_tables.py
    python scripts/generate_latex_tables.py --out PHD/tables/
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BENCH = REPO_ROOT / "validation/benchmarks"


def _esc(s: str) -> str:
    """Escape LaTeX specials conservatively."""
    return (str(s)
            .replace("\\", "\\textbackslash{}")
            .replace("&", "\\&")
            .replace("%", "\\%")
            .replace("_", "\\_")
            .replace("#", "\\#")
            .replace("$", "\\$"))


def calibration_table() -> str:
    p = BENCH / "calibration_regression.json"
    if not p.exists():
        return "% calibration_regression.json missing\n"
    rows = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Op\\textsuperscript{3} calibration regression against published reference frequencies.}",
        "\\label{tab:op3_calibration_regression}",
        "\\begin{tabular}{lrrrrc}",
        "\\toprule",
        "Example & $f_1^\\text{Op3}$ (Hz) & $f_1^\\text{ref}$ (Hz) & "
        "Error & Tol. & Status \\\\",
        "\\midrule",
    ]
    for r in rows:
        f = r["f1_hz"]
        ref = r["reference_hz"]
        err = r["error_fraction"] * 100
        tol = r["tolerance"] * 100
        name = _esc(r["example"].replace("_", " "))
        status = "\\checkmark" if r["status"] == "PASS" else "$\\times$"
        lines.append(
            f"{name} & {f:.4f} & {ref:.4f} & "
            f"{err:+.1f}\\% & $\\pm${tol:.0f}\\% & {status} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    return "\n".join(lines) + "\n"


def dnv_table() -> str:
    p = BENCH / "dnv_st_0126_conformance.json"
    if not p.exists():
        return "% dnv_st_0126_conformance.json missing\n"
    data = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{DNV-ST-0126 conformance audit of Op\\textsuperscript{3} examples.}",
        "\\label{tab:dnv_conformance}",
        "\\begin{tabular}{llc}",
        "\\toprule",
        "Example & Clause & Status \\\\",
        "\\midrule",
    ]
    for ex in data:
        for ch in ex["checks"]:
            mark = {"PASS": "\\checkmark", "FAIL": "$\\times$",
                    "WARNING": "$\\triangle$",
                    "NOT_APPLICABLE": "--"}.get(ch["status"], "?")
            lines.append(
                f"{_esc(ex['example'])} & {ch['id']} {_esc(ch['title'])} & {mark} \\\\"
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.extend(["\\end{tabular}", "\\end{table}"])
    return "\n".join(lines) + "\n"


def iec_table() -> str:
    p = BENCH / "iec_61400_3_conformance.json"
    if not p.exists():
        return "% iec_61400_3_conformance.json missing\n"
    data = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{IEC 61400-3 structural and foundation provisions.}",
        "\\label{tab:iec_conformance}",
        "\\begin{tabular}{llc}",
        "\\toprule",
        "Example & Clause & Status \\\\",
        "\\midrule",
    ]
    for ex in data:
        for ch in ex["checks"]:
            if ch["id"].startswith("I8.3"):
                continue   # DLC coverage is documented separately
            mark = {"PASS": "\\checkmark", "FAIL": "$\\times$",
                    "WARNING": "$\\triangle$",
                    "NOT_APPLICABLE": "--"}.get(ch["status"], "?")
            lines.append(
                f"{_esc(ex['example'])} & {ch['id']} {_esc(ch['title'])} & {mark} \\\\"
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.extend(["\\end{tabular}", "\\end{table}"])
    return "\n".join(lines) + "\n"


def sensitivity_table() -> str:
    p = BENCH / "calibration_tornado_summary.json"
    if not p.exists():
        return "% calibration_tornado_summary.json missing\n"
    data = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Op\\textsuperscript{3} first-mode sensitivity tornado.}",
        "\\label{tab:sensitivity_tornado}",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Example & Parameter & $-$10\\% & $+$10\\% & Swing \\\\",
        "\\midrule",
    ]
    for ex in data:
        for row in ex["rows"][:5]:   # top 5 per example
            lines.append(
                f"{_esc(ex['example'][:20])} & {_esc(row['parameter'])} & "
                f"{row['df_minus_pct']:+.2f}\\% & "
                f"{row['df_plus_pct']:+.2f}\\% & "
                f"{row['swing_pct']:+.2f}\\% \\\\"
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.extend(["\\end{tabular}", "\\end{table}"])
    return "\n".join(lines) + "\n"


def pisa_crossval_table() -> str:
    p = BENCH / "pisa_cross_validation.json"
    if not p.exists():
        return "% pisa_cross_validation.json missing\n"
    data = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{PISA cross-validation against published test piles.}",
        "\\label{tab:pisa_crossval}",
        "\\begin{tabular}{lrrrl}",
        "\\toprule",
        "Case & $D$ (m) & $L$ (m) & Op\\textsuperscript{3} $K_{xx}$ (N/m) & Status \\\\",
        "\\midrule",
    ]
    for r in data:
        g = r["geometry"]
        lines.append(
            f"{_esc(r['case'])} & {g['D_m']:.2f} & {g['L_m']:.2f} & "
            f"${r['op3_Kxx_N_per_m']:.2e}$ & {_esc(r['status_Kxx'])} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    return "\n".join(lines) + "\n"


def oc6_table() -> str:
    p = BENCH / "oc6_phase2_benchmark.json"
    if not p.exists():
        return "% oc6_phase2_benchmark.json missing\n"
    data = json.loads(p.read_text(encoding="utf-8"))
    lines = [
        "% Auto-generated",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{OC6 Phase II benchmark (Bergua 2021) status.}",
        "\\label{tab:oc6_phase2}",
        "\\begin{tabular}{llrl}",
        "\\toprule",
        "Case & Quantity & Op\\textsuperscript{3} & Status \\\\",
        "\\midrule",
    ]
    for r in data:
        val = f"${r['op3_value']:.3e}$" if r.get("op3_value") else "--"
        lines.append(
            f"{_esc(r['case'])} & {_esc(r['quantity'])} & {val} & {_esc(r['status'])} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    return "\n".join(lines) + "\n"


TABLES = {
    "calibration_regression_table.tex": calibration_table,
    "dnv_conformance_table.tex": dnv_table,
    "iec_conformance_table.tex": iec_table,
    "sensitivity_tornado_table.tex": sensitivity_table,
    "pisa_cross_val_table.tex": pisa_crossval_table,
    "oc6_phase2_table.tex": oc6_table,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="PHD/tables",
                    help="Output directory for .tex files")
    args = ap.parse_args()
    out = REPO_ROOT / args.out
    out.mkdir(parents=True, exist_ok=True)
    print(f"Writing LaTeX tables to {out}")
    for name, fn in TABLES.items():
        (out / name).write_text(fn(), encoding="utf-8")
        print(f"  [OK] {name}")
    print(f"\n{len(TABLES)} tables written")


if __name__ == "__main__":
    main()
