"""
Update SHA-256 fingerprints in dissertation Appendix D (Task 22).

The Appendix D "Code embed" table in the dissertation pins specific
Op^3 source files by their SHA-256 fingerprint so that the
dissertation reader can verify any quoted code is identical to the
committed source. This script regenerates those fingerprints against
the current HEAD and rewrites the appendix markdown in place.

Run:
    python scripts/update_appendix_d_shas.py
    python scripts/update_appendix_d_shas.py --dry-run

The target file is ``PHD/appendices/appendix_d_code_embed.md`` and
the target table rows have the form

    | `op3/standards/pisa.py` | ... | `abcdef0123...` |

The script updates only the third column (the fingerprint) and
leaves the description column intact.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_files() -> dict[str, str]:
    """The canonical code-embed manifest: path -> SHA-256."""
    targets = [
        "op3/__init__.py",
        "op3/foundations.py",
        "op3/composer.py",
        "op3/opensees_foundations/builder.py",
        "op3/opensees_foundations/tower_loader.py",
        "op3/standards/pisa.py",
        "op3/standards/cyclic_degradation.py",
        "op3/standards/hssmall.py",
        "op3/openfast_coupling/soildyn_export.py",
        "op3/uq/propagation.py",
        "op3/uq/pce.py",
        "op3/uq/bayesian.py",
    ]
    out = {}
    for rel in targets:
        p = REPO_ROOT / rel
        if p.exists():
            out[rel] = sha256(p)
        else:
            out[rel] = "MISSING"
    return out


def write_manifest(dest: Path, manifest: dict[str, str]) -> None:
    lines = [
        "# Op^3 Appendix D code-embed manifest",
        "",
        "Auto-generated by `scripts/update_appendix_d_shas.py`.",
        "",
        "| File | SHA-256 |",
        "|---|---|",
    ]
    for path, h in manifest.items():
        lines.append(f"| `{path}` | `{h}` |")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def patch_appendix_d(appendix: Path, manifest: dict[str, str],
                     dry_run: bool = False) -> int:
    if not appendix.exists():
        print(f"Appendix D markdown not found at {appendix}")
        print("Writing a fresh manifest instead.")
        return 0
    text = appendix.read_text(errors="replace")
    n_updated = 0
    for rel, h in manifest.items():
        # Match: | `path` | ... | `oldhash` |   (table row)
        pattern = rf"(\|\s*`{re.escape(rel)}`\s*\|[^|]*\|\s*`)[a-f0-9]{{8,64}}(`\s*\|)"
        new_text, n = re.subn(pattern, rf"\g<1>{h}\g<2>", text, count=1)
        if n > 0:
            text = new_text
            n_updated += 1
    if not dry_run:
        appendix.write_text(text, encoding="utf-8")
    return n_updated


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--appendix",
                    default="PHD/appendices/appendix_d_code_embed.md")
    ap.add_argument("--manifest",
                    default="docs/CODE_EMBED_MANIFEST.md",
                    help="Canonical manifest file (always regenerated)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    manifest = canonical_files()
    print("Canonical SHA-256 manifest:")
    for rel, h in manifest.items():
        tag = h if h == "MISSING" else h[:16] + "..."
        print(f"  {rel:<46} {tag}")

    manifest_path = REPO_ROOT / args.manifest
    if not args.dry_run:
        write_manifest(manifest_path, manifest)
        print(f"\nManifest written: {manifest_path}")

    appendix_path = REPO_ROOT / args.appendix
    n = patch_appendix_d(appendix_path, manifest, dry_run=args.dry_run)
    print(f"\n{n} row(s) updated in {appendix_path}")


if __name__ == "__main__":
    main()
